# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Modules related to a cooperative registry (subscribtion requests,
    share transfer, ...).
repo_name: Cooperative
repo_slug: cooperative
repo_website: https://github.com/OCA/cooperative
travis_apt_packages: []
travis_apt_sources: []

